  %YAML:1.0

  #--------------------------------------------------------------------------------------------
  # ORB Parameters
  #--------------------------------------------------------------------------------------------

  # ORB Extractor: Number of features per image
  ORBextractor.nFeatures: 1500

  # ORB Extractor: Scale factor between levels in the scale pyramid
  ORBextractor.scaleFactor: 1.05

  # ORB Extractor: Number of levels in the scale pyramid
  ORBextractor.nLevels: 4

  # ORB Extractor: Fast threshold
  # Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
  # Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
  # You can lower these values if your images have low contrast
  ORBextractor.iniThFAST: 20
  ORBextractor.minThFAST: 7

  #ORB Extractor: Set whether to distribute keypoints per octave
  # If set to true(1), keypoints will be distributed per image octave
  # If set to false(0), the keypoint vector will be flattened first, then distributed
  ORBextractor.distributePerLevel: 1

  #-----------------------------------------------
  # Display properties for keypoint visualization
  #-----------------------------------------------
  Line.thickness: 1

  Color.b: 0
  Color.g: 180
  Color.r: 160

  Circle.radius: 4

  drawAngular: 1